CharityApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('charity/', include('charity.urls')),
    path('providers/', include('providers.urls')),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, settings.STATIC_ROOT)

charity/urls.py
from django.urls import path
from . import views

app_name = "charity"

urlpatterns = [
    path('', views.dashboard, name = "dashboard"),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.ShowIndex, name= 'home'),
    path('contact/', views.ShowContact, name= 'contact'),
    path('reel/', views.ShowReel, name= 'reel'),
    path('blogs/', views.ShowBlog, name= 'blogs'),
    path('volunteer-join/', views.VolunteerJoin, name= 'volunteer'),
    path('user/', views.ShowUserPage, name= 'dashboard'),
]

providers/urls.py
from django.urls import path
from . import views

app_name = "providers"

urlpatterns = [
    path('', views.dashboard, name = "dashboard"),
    
]

users/urls.py
from django.urls import path
from . import views

# app_name = "users"

urlpatterns = [
    path('', views.loginPage, name = "login"),
    path('signup/', views.signUp, name = "signup"),
    path('logout/', views.logoutUser, name = "logout"),
    # path('index/', views.index),
    # path('charity/', views.charity_acc),
    # path('provider/', views.provider_acc),
]

charity/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

providers/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

# class UserProfile(models.Model):  

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
# from .models import

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name','email', 'password1','password2']

charity/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from decorators import allowed_users

# Create your views here.
@login_required(login_url='login')
@allowed_users(allowed_roles=['charity'])
def dashboard(request):
    return render(request, 'charity/charity-acc.html')

main/views.py
from django.shortcuts import render
# from ..users.decorators import unauthenticated_user, allowed_users, admin_only
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url='login')
def ShowIndex(request):
    return render(request, 'main/index.html')

@login_required(login_url='login')
def ShowContact(request):
    return render(request, 'main/contact.html')

@login_required(login_url='login')
def ShowReel(request):
    return render(request, 'main/showreel.html')

@login_required(login_url='login')
def ShowBlog(request):
    return render(request, 'main/blogs.html')

@login_required(login_url='login')
def ShowUserPage(request):
    return render(request, 'main/user-acc.html')

@login_required(login_url='login')
def VolunteerJoin(request):
    return render(request, 'main/volunteer-join.html')

providers/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from decorators import allowed_users
# Create your views here.
@login_required(login_url='login')
@allowed_users(allowed_roles=['provider'])
def dashboard(request):
    return render(request, 'providers/provider-acc.html')

users/views.py
from ast import If
import email
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse

from .forms import CreateUserForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group

from django.contrib import messages

from decorators import unauthenticated_user, allowed_users, admin_only

# Create your views here.
@unauthenticated_user
def signUp(request):
    form = CreateUserForm()

    if request.method == 'POST':
        radioSelection = request.POST.get('select-user-type')
        
        query_set = Group.objects.filter(name = radioSelection)
        
        group = Group()
        if query_set.count() == 0:
            group = Group(name=radioSelection)
            group.save() # Create a sample group.
        else:
            group = query_set[0]

        

        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = request.POST.get("username")
            password = request.POST.get("password1")

            user = authenticate(username=user_name,password=password)

            if user is not None:
                login(request,user)
                user = request.user # get Some User.
                user.groups.add(group)
            messages.success(request, 'Account was created for '+  request.POST.get('username'))
            return redirect("login")

    context = {'form': form}
    return render(request, 'users/signup.html',context)

@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username= request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username = username, password= password)
        
        if user is not None:
            login(request, user)
            if request.user.groups.filter(name="provider").exists():
                return redirect('providers:dashboard')
            elif request.user.groups.filter(name="charity").exists():
                return redirect('charity:dashboard')
            else:
                return redirect('main:dashboard')
        else:
            messages.info(request,'Username or Password incorrect')

    return render(request, 'users/login.html')

def logoutUser(request):
    logout(request)
    return redirect(loginPage)




# def charity_acc(request):
#     return render(request, 'users/charity-acc.html')

# def provider_acc(request):
#     return render(request, 'users/provider-acc.html')

# def user_acc(request):
#     return render(request, 'users/user-acc.html')

charity/templates/charity/charity-acc.html
{%  extends  'main/main.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet " href="{% static 'charity/styles/charity-acc.css'%}">

    <main>
        <h1 class="welcome-message">Welcome to your account, {{ user.get_full_name }}</h1>
        <aside class="acc-info-responsive">
            <h2 class="user-name">{{ user.get_full_name }}</h2>
            <p class="email">E-mail Address<br> <span class="email-data">{{ user.email }}</span></p>
            <p class="mobile">Mobile number<br> <span class="mobile-data">011 2345 6789</span></p>
            <p class="points">Your Points<br> <span class="points-data">850</span></p>

        </aside>
        <div class="box1">
            <div class="acc-card">
                <img class="card-img" src="{% static 'charity/media/hands.jpg'%}" alt="">
                <p class="card-p">help us to make impact changes in the socaity</p>
            </div>
            <div class="box-content">
                <h2>Your donation will make us stronger</h2>
                <p>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit</p>
                <a class="supply-btn-link" href="#supply"></a> <button class="supply-btn" value="ask for supplies">ask for supplies</button>
            </div>
        </div>

        <aside class="acc-info">
            <h2 class="user-name">{{ user.get_full_name }}</h2>
            <p class="email">E-mail Address<br> <span class="email-data">{{ user.email }}</span></p>
            <p class="mobile">Mobile number<br> <span class="mobile-data">011 2345 6789</span></p>
            <p class="points">Your Points<br> <span class="points-data">850</span></p>

        </aside>
    </main>

    <div class="box2">
        <!-- <div class="elements-holder2"> -->
        <div id="supply" class="box2-left-elements">
            <p class="left-content-p">It’s time to make your change into the world</p>
            <h1 class="logo-word">FoodManage</h1>
        </div>
        <div class="box2-middle-elements">
            <label class="food-amount-label" for="food-amount" aria-required="true">Food Amount (Kg)</label>
            <input class="food-amount" type="number" name="food amount" required> <br>

            <label class="user-location" for="location" aria-required="true">Your Location</label>
            <input class="location" type="text" name="location" required> <br>
            <p class="form-text">We’ll notice you with pick up information</p>

            <input class="submit-btn" type="submit">

        </div>
        <div class="box2-right-elements">
            <div class="card-bg-img"></div>
        </div>
        <!-- </div> -->
    </div>


    <script src="{% static 'charity/js/charity-acc.js'%}"></script>
    {% endblock %}

main/templates/main/blogs.html
{%  extends  'main/main.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet " href="{% static '/main/styles/blogs.css' %}">
    <main class="center-elements">
        <div class="left-div">
            <h1 class="blogs-header">Blogs</h1>
            <p class="blogs-p">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quiepakis nostrud exercitation ullamco laboris nsi ut aliquip ex ea comepmodo consetquat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cfgillum dolore eutpe fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt inpeku culpa qui officia deserunt mollit anim id est laborum. <br> Sed ut
                perspiciatis unde omnis iste natus error sit voluptatem accusantium poeyi doloremque laudantium, totam rem aperiam, eaque ipsa quae apsb illo inventore veritatis et quasi architecto beiatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem
                quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, seprid quia non
                numquam eius modi tempora incidunt ut labore et dolore magnam aliqueam quaerat voluptatem.</p>
        </div>
        <div class="comments">
            <p class="comment-word">Comment</p>
            <textarea placeholder="comment" for="comment"></textarea> <br>
            <input class="submit-btn" type="submit" value="submit">
            <div class="user-comments">
                <div class="user-info">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    <p class="user-name">Elisa john</p>
                    <p class="comment-time">1 hour ago</p>
                </div> <br>
                <p class="user-comment">qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, seprid quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliqueam quaerat voluptatem.</p>
            </div>

            <div class="user-comments">
                <div class="user-info">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    <p class="user-name">Elisa john</p>
                    <p class="comment-time">1 hour ago</p>
                </div> <br>
                <p class="user-comment">qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, seprid quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliqueam quaerat voluptatem.</p>
            </div>

            <div class="user-comments">
                <div class="user-info">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    <p class="user-name">Elisa john</p>
                    <p class="comment-time">1 hour ago</p>
                </div> <br>
                <p class="user-comment">qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, seprid quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliqueam quaerat voluptatem.</p>
            </div>

            <div class="user-comments">
                <div class="user-info">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    <p class="user-name">Elisa john</p>
                    <p class="comment-time">1 hour ago</p>
                </div> <br>
                <p class="user-comment">qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, seprid quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliqueam quaerat voluptatem.</p>
            </div>
        </div>
    </main>




    
    {% endblock %}

main/templates/main/contact.html
{%  extends  'main/main.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet " href="{% static '/main/styles/contact.css' %}">
    <!-- contact -->

    <section id="contact">

        <h1 class="section-header">CONTACT</h1>

        <div class="contact-wrapper">

            <!---------------- 

    CONTACT PAGE LEFT 
  
    ----------------->

            <form id="contact-form" class="form-horizontal" role="form">

                <div class="form-group">
                    <div class="col-sm-12">
                        <input type="text" class="form-control" id="name" placeholder="NAME" name="name" value="" required>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-12">
                        <input type="email" class="form-control" id="email" placeholder="EMAIL" name="email" value="" required>
                    </div>
                </div>

                <textarea class="form-control" rows="10" placeholder="MESSAGE" name="message" style="resize: unset;" required></textarea>

                <button class="btn btn-primary send-button" id="submit" type="submit" value="SEND">
      <div class="button">
        <!-- <i class="fa fa-paper-plane"></i> -->
        <span class="send-text">SEND</span>
      </div>
    
    </button>

            </form>

            <!---------------- 

    CONTACT PAGE RIGHT 
  
    ----------------->

            <div class="direct-contact-container">

                <ul class="contact-list">
                    <li class="list-item"><i class="fas fa-map-marker-alt fa-2x"></i><span class="contact-text place">Giza, Egypt</span></i>
                    </li>

                    <li class="list-item"><i class="fa fa-phone fa-2x"><span class="contact-text phone"><a href="tel:01067300073" title="Give me a call or text me">01067300073</a></span></i></li>

                    <li class="list-item"><i class="fa fa-envelope fa-2x"><span class="contact-text gmail"><a href="mailto:#crvd.info@gmail.com" title="Send me an email">crvd.info@gmail.com</a></span></i></li>

                </ul>

                <hr>
                <ul class="social-media-list">
                    <!-- <li>
                <a href="#" target="_blank" class="contact-icon">
                    <i class="fa fa-github" aria-hidden="true"></i></a>
            </li> -->
                    <a href="https://www.facebook.com/CRVD-112601321231363" class="contact-icon">
                        <li>
                            <i class="fab fa-twitter" aria-hidden="true"></i>
                        </li>
                    </a>
                    <a href="https://www.instagram.com/crvd.info/" target="_blank" class="contact-icon">
                        <li>
                            <i class="fab fa-instagram" aria-hidden="true"></i>
                        </li>
                    </a>
                    <a href="https://www.facebook.com/CRVD-112601321231363" target="_blank" class="contact-icon">
                        <li>
                            <i class="fab fa-facebook-f" aria-hidden="true"></i>
                        </li>
                    </a>
                </ul>
                <hr>

                <div class="copyright">&copy; ALL RIGHTS RESERVED FOR FoodManage</div>

            </div>
        </div>
    </section>


    {% endblock %}
    <script src="{% static '/main/js/contact.js' %}"></script>

main/templates/main/footer.html
<footer>
    <div>
        <h1 class="footer-logo">FoodManage</h1>
        <!-- <img class="footer-logo" src="imgs/CRVD-LOGOfinal.png" alt=""> <br> -->
        <p class="footer-text">Stay informed, subscribe to our OFFERS!</p>
        <form>
            <label for="fname">First Name</label>
            <input type="text" id="fname" name="fname"> <br>
            <button type="submit">Submit</button>

        </form>
    </div>
    <div class="social-media-holder">
        <h1 class="social-media">Social Media</h1>
        <div class="flex-div">
            <a class="social-item link-items" href="https://www.facebook.com/CRVD-112601321231363">Facebook</a>
            <a class="social-item link-items" href="https://www.instagram.com/crvd.info/">Instagram</a>
            <a class="social-item link-items" href="https://www.facebook.com/CRVD-112601321231363">Twitter</a>
        </div>
    </div>
    <div class="privacy-holder">
        <h1 class="Policy">Pages</h1>
        <div class="flex-div">
            <a class="policy-item link-items" href="{% url 'main:reel' %}">Showreel</a>
            <a class="policy-item link-items" href="{% url 'main:blogs' %}">Blog</a>
            <a class="policy-item link-items" href="{% url 'main:contact' %}">Contact Us</a>
            <!-- <a class="policy-item link-items" href="volunteer.html">Volunteer</a> -->
            <!-- <a class="policy-item link-items" href="#">Partners</a> -->
        </div>
    </div>
    <div class="location-holder">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13818.016403879974!2d30.99910269703188!3d30.02239252807758!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14585a182c7fbc0b%3A0xa6dc4c3139bb0c14!2sFavilla%20Lounge!5e0!3m2!1sen!2seg!4v1569757358329!5m2!1sen!2seg"
            width="100%" height="220" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        <a href="tel:01067300073" title="Give me a call or text me"> <button class="call-btn"><span>Call NOW</span></button></a>

    </div>
</footer>

main/templates/main/index.html
{%  extends  'main/main.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet " href="{% static '/main/styles/index.css' %}">
    <section class="landing-section">
        <div class="left-div">
            <h1 class="landing-text">Cutting food waste is a delicious way of saving money, helping to feed the world and protect the planet.</h1>
            <a href="{% url 'main:volunteer'%}"><button class="volunteer-btn">Volunteer</button></a>
            <a href="#"><button class="join-btn">Join Us</button></a>
        </div>
        <img class="landing-img" src="{% static 'main/media/landing-img.jpg'%}" alt="">
    </section>
    <div class="company-numbers">
        <div class="black-overlay"></div>
        <p class="number1">Cooperators<br>+300</p>
        <p class="number2">Charities<br>+500</p>
        <p class="number3">Recycled food<br>+10000</p>
    </div>
    <section id="vision-and-mission" class="vision-and-mission">
        <h1 class="vision-header">Vision & Mission</h1>
        <div class="flex-holder">
            <img class="vision-section-img" src="{% static 'main/media/vision-and-mission.jpg'%}" alt="myimg">
            <p class="vision-section-p">Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.
                Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam
                consequat sunt nostrud amet.Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.Amet minim mollit non deserunt ullamco
                est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.</p>
        </div>
    </section>
    <section id="join-us" class="join-us-section">
        <h1 class="join-us-header">Join Us</h1>
        <div class="join-content-holder">
            <div>
                <p class="join-section-p">World hunger is on the rise, despite the work of people and organizations (such as the UN and World Bank) to tackle this problem. The global spend to make worldwide access to food possible reaches into billions of dollars. By looking at
                    this problem, one could easily assume that there’s a shortage of food. But that’s not the case. The problem is food waste. These food waste quotes can inspire us to think about how much food we waste and could prevent from going to
                    landfill.
                    <br> The world produces enough food to keep everyone alive today well fed. According to the Food and Agriculture Organization of the UN, we have enough food to feed 10 billion people1. However, this food doesn’t get to everyone because
                    of the wasteful behaviours of some. This waste starts from the level of the farmer to us, the consumers.
                </p>
                <a href="#"></a><button class="join-btn" value="Join Us">Join Us</button>
            </div>
            <img class="join-section-img" src="{% static 'main/media/packaging.jpg'%}" alt="myimg">
        </div>
    </section>

    <section id="events">
        <div class="about-content container">
            <div class="about-info">
                <h2 data-aos="fade-in">Our Events</h2>
                <p data-aos="zoom-in" class="about-info-p">
                    PIXA STEEL has delivered engineering, project management and site studies services in EGYPT. PIXA STEEL has delivered engineering, project management and site studies services in EGYPT. PIXA STEEL has delivered engineering, project management and site
                    studies services in EGYPT.<br><br> PIXA STEEL has delivered engineering, project management and site studies services in EGYPT. PIXA STEEL has delivered engineering, project management and site studies services
                    in EGYPT. PIXA STEEL has delivered engineering, project management and site studies services in EGYPT. PIXA STEEL has delivered engineering, project management and site studies services in EGYPT.
                </p>

            </div>
            <div class="about-images">

                <img class="img1" data-aos="slide-right" src="{% static 'main/media/alexander-schimmeck-YpOhhVGPkyQ-unsplash.jpg' %}">
                <img class="img2" data-aos="slide-left" src="{% static 'main/media/alexander-schimmeck-z_GQ5vX3flc-unsplash.jpg' %}">
                <img class="img3" data-aos="slide-right" src="{% static 'main/media/bernard-hermant-dclPEtMVdK8-unsplash.jpg' %}">
                <img class="img4" data-aos="slide-left" src="{% static 'main/media/warren-wong-J33qmCVr02A-unsplash.jpg' %}">
                <img class="img1" data-aos="slide-right" src="{% static 'main/media/packaging.jpg' %}">
                <img class="img3" data-aos="slide-left" src="{% static 'main/media/jack-church-LZ8NzZrByts-unsplash.jpg' %}">
                <img class="img4" data-aos="slide-right" src="{% static 'main/media/larm-rmah-AEaTUnvneik-unsplash.jpg' %}">
                <img class="img5" data-aos="slide-left" src="{% static 'main/media/katt-yukawa-K0E6E0a0R3A-unsplash.jpg' %}">
            </div>
        </div>
    </section>



    {%  include 'main/footer.html' %}
{% endblock %}

main/templates/main/navbar.html
<header>
    <div class="logo-holder"> <a class="company-logo" href="{% url 'main:home' %}">FoodManage</a></div>
    <nav class="navbar">
        <ul class="nav-items">
            <li class="nav-item"><a href="{% url 'main:home' %}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="#vision-and-mission" class="nav-link">V & M</a></li>
            <li class="nav-item"><a href="#" class="nav-link">Join Us</a></li>
            <li class="nav-item"><a href="#events" class="nav-link">Events</a></li>
            <li class="nav-item"><a href="{% url 'main:contact' %}" class="nav-link">Contact Us</a></li>
            <li class="nav-item  "><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </nav>
    <div class="menu-toggle">
        <i class="bx bx-menu"></i>
        <i class="bx bx-x"></i>
    </div>
</header>

main/templates/main/showreel.html
{%  extends  'main/main.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet " href="{% static '/main/styles/showreel.css' %}">
    <div class="video-media">
        <video width="100%" id="myVideo" controls>
            <source src="{% static '/main/media/Separate food waste and recycle for a healthy planet.mp4' %}">
        </video>
    </div>


    <script src="{% static '/main/js/showreel.js' %}"></script>
{% endblock %}

main/templates/main/volunteer-join.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="keywords" content="Food Manage company">
    <meta name="description" content="FoodManage company">
    <!-- stylesheets css -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet " href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css " integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2 " crossorigin="anonymous ">
    <meta name="description" content="Maqam Studios is one of the largest Media Production Agencies in the Middle East, Which produced the best three films: 122, The Fourth Pyramids and Monkey Talks.">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet " href="{% static 'main/styles/volunteer.css'%}">
    <link rel="stylesheet" href="css/et-line-font.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />

    <link rel="icon " type="image/png " href="images/warehouse-old-construction-beams-country_1127-2786.jpg " />

    <link rel="stylesheet " href="https://unpkg.com/aos@next/dist/aos.css " />
</head>

<body>

    <body>
        <div class="background-img"></div>
        <div class="left-div">
            <a class="logo-img" href="{% url 'main:home' %}">FoodManage</a> <br>
            <p class="join-word">It’s time to make your change into the world</p>
        </div>
        <form action="">
            <div class="form-content">
                <h3 class="signin">Suppot FoodManage’s work for the socaity</h3>
                <p class="new-user">We are on the frontlines every day waging fierce courtroom battles and hard-hitting campaigns in defense of our climate, public health, wildlife, and wild places.</p>
                <!-- <div class="user-type">
                    <input class="radio-btn" type="radio" name="select-user-type" value="regular" for="regular" checked>
                    <label for="regular">Regular</label><br>
                    <input class="radio-btn" type="radio" name="select-user-type" value="provider" for="provider">
                    <label for="provider">Provider</label><br>
                    <input class="radio-btn" type="radio" name="select-user-type" value="individual provider" for="individual provider">
                    <label for="individual provider">Provider</label><br>
                    <input class="radio-btn" type="radio" name="select-user-type" value="charity" for="charity">
                    <label for="charity">Charity</label><br>
                </div> -->

                <div class="regular-user">
                    <input class="email-input" type="email" placeholder="E-mail address" required>
                    <input class="Provider-name" type="text" placeholder="volunteer name" required>
                    <input class="description" type="text" placeholder="How can you help us?" required>
                    <input class="mobile-number" type="tel" placeholder="Mobile Number" required>
                    <!-- <input class="description" type="text" placeholder="How can you help us?" required> -->

                </div>
                <p>Can you take a part of the Delivery process</p>
                <input class="radio-btn" type="radio" name="select-user-type" value="yes" for="regular" checked>
                <label for="regular">Yes, i can</label>
                <input class="radio-btn" type="radio" name="select-user-type" value="no" for="provider">
                <label for="provider">No, i can't</label>
                <!-- <div class="charity-provider">
                    <input class="email-input" type="email" placeholder="E-mail address" required>
                    <input class="orgnization-name" type="text" placeholder="Orgnization name" required>
                    <input class="password" type="password" placeholder="password" required>
                    <input class="mobile-number" type="tel" placeholder="Mobile Number" required>
                    <input class="Admin-name" type="text" placeholder="Admin. Name" required>
                </div> -->
                <input type="submit" name="Submit" id="submit-btn">
            </div>
        </form>



        <script src="{% static 'main/js/volunteer.js' %}"></script>

    </body>

</html>